### ISSUE TITLE
This doesn't work anymore

### ISSUE THREAD

**Issue by RayBB** [WoodburyShortridge/southwest#1]
Just wanted to let people know that this version has the wrong id for the button so won't work anymore.

Here's a working version someone made :)
https://github.com/brandongoldman/southwest-checkin/blob/master/checkin.js

**Comment by woodybury** [comment]
thanks @RayBB I will update the button id

**Comment by woodybury** [comment]
the btn id is updated. Thanks again @RayBB ;)
